### ISSUE TITLE
CSS not working on 'Notes on Using ARIA in HTML' with Safari

### ISSUE THREAD

**Issue by Veyfeyken** [w3c/tr-design#92] opened 2016-04-01 12:40 UTC
https://www.w3.org/TR/aria-in-html/ 
Only occurs in Safari. 
Screenshot: http://images.anysurfer.be/gijs/aria-html.png

**Comment by tripu** [comment] 2016-04-03 12:46
Are you sure it's not a caching issue, @Veyfeyken?
Can you spot any errors in the JS console or when loading resources?

**Comment by Veyfeyken** [comment] 2016-04-05 13:04
Can it be a caching issue if it also occurs in a private window?

Found this error in the console:

[blocked] The page at https://www.w3.org/TR/aria-in-html/ was not allowed to run insecure content from http://www.w3.org/StyleSheets/TR/W3C-WD.

**Comment by tripu** [comment] 2016-04-05 19:09
Ah, I see, @Veyfeyken.

Perhaps the cause is in the way Safari handles `upgrade-insecure-requests`&hellip;

The stylesheet is linked from the document this way:

``` html
<link href="http://www.w3.org/StyleSheets/TR/W3C-WD" rel="stylesheet">
```

**Comment by tripu** [comment] 2016-04-13 08:20
@Veyfeyken, Safari doesn't do any `upgrade-insecure-requests`. If the page is retrieved using HTTPS, that link will be blocked, or will generate a mixed-content warning.

The resource has to be included either using an agnostic protocol (ie, `//…`) or using HTTPS.

I'm closing this one, as it's not about the new TR design.

**Closed as completed by tripu** 2016-04-13 08:20 UTC
Labels: question
