### ISSUE TITLE
Accessibility concerns

### ISSUE THREAD

**Issue by thierryk** [w3c/tr-design#57] opened 2016-02-19 19:53 UTC
I've noticed a few issues:
- Keyboard navigation:
  - In Chrome, all links to "named" anchors are broken. For example, "clicking" on the "Jump to Table Of Content" link and then hitting the `tab` key puts the focus back on that link rather than focusing onto an element of the TOC. That's an old Chrome bug that can be "fixed" by adding `tabindex="-1"` to the "named" anchor (i.e. `<nav id="toc" tabindex="-1">`). 
  - The visual layout does not really match source order as the TOC **shows** to the left of `div.head` (as in "before the header") even though it comes **after** it in the markup. This may be confusing to some users (i.e. sighted keyboard users). Also, it seems that for SR users best practice is to deliver the [same experience](https://twitter.com/jsutt/status/692104162905952257) across the board&mdash;meaning if sighted users perceive the TOC as being before the "header" then SR users should perceive that as well.  
- The TOC "nav" may be better positioned at the top left of the viewport rather than its bottom because those links could go unnoticed on large screens.
- The "Pop Out Sidebar" link could be hidden from screen-reader users as its purpose is purely visual. 
- I'd not wrap the "jump links" inside a `nav` element as [only sections that consist of major navigation blocks are appropriate for the nav element](http://html5doctor.com/nav-element/). 

In my opinion, pages like these are very difficult to navigate for keyboard users. Not only because the visual sequence is different than the natural tab order but also because once a user selects a jump link within the TOC and reaches that section by tabbing out&mdash;it is very laborious to reach back to the TOC. This is why I believe the use of [`accesskey`](http://webaim.org/techniques/keyboard/accesskey) may help here.

Regarding the jump links themselves, I think the second item (the one that toggles the TOC) should be a **button** instead of a _link_. And I'd not rely on `title` to convey the text, I'd rather **hide** the arrows from SR users and give them _plain text_ ([visually-hidden](https://developer.yahoo.com/blogs/ydn/clip-hidden-content-better-accessibility-53456.html)). Then you can display that text on mouseover rather than using pseudo-elements. 

So instead of this:

``` html
<nav id="toc-nav">
  <a id="toc-jump" href="#toc">
    <abbr title="Jump to Table of Contents">↑</abbr>
  </a>
  <a id="toc-toggle" class="toc-toggle" href="#toc">
    <abbr title="Pop Out Sidebar">→</abbr>
  </a>
</nav>
```

I'd go with something like this:

``` html
<div id="toc-nav">
  <a id="toc-jump" href="#toc">
    <b class="visually-hidden">Jump to Table of Contents</b>
    <b aria-hidden="true">↑</b>
  </a>
  <button id="toc-toggle" class="toc-toggle">
    <b class="visually-hidden">Pop Out Sidebar</b>
    <b aria-hidden="true">→</b>
  </button>
</div>
```

or this if we think the toggle button is of no use to SR users: 

``` html
<div id="toc-nav">
  <a id="toc-jump" href="#toc">
    <b class="visually-hidden">Jump to Table of Contents</b>
    <b aria-hidden="true">↑</b>
  </a>
  <button id="toc-toggle" class="toc-toggle" aria-hidden="true">
    <b class="visually-hidden">Pop Out Sidebar</b>
    <b>→</b>
  </button>
</div>
```

As a side note, "Collapse Sidebar" may not be the right wording here as the element does not _collapse_ per se; to the contrary, it goes back into flow. I'm not sure that word helps create the proper mental model for how that TOC behaves.

**Comment by fantasai** [comment] 2016-02-20 04:35
Okay, so
- This is not a regression from the current situation, and it's clearly a browser bug. Chrome should be marking it as critical and prioritizing accordingly. It _is_ a critical accessibility bug, and should be treated as such, not hacked around by us here.
- Despite that the ToC is to the left of the main content, visual users do not read pages 100% left-to-right top-to-bottom. Other factors come into play, such as size and color: visual perception is not linear. The first thing a sighted user will notice is the title of the document and the spec metadata block. And accordingly, these are the first things in the source. (The visual user will notice the ToC before the Status of This Document boilerplate junk, it's true, but fixing that problem isn't something I can tackle for this release. It is, however on the to-do list for later. Just not this year, since it requires major changes to pubrules.)
- I think the ToC nav buttons need to be near the ToC, and putting them at the bottom interferes less with a) the status banner in the top left corner and b) the rest of the content, which is the intense focus of most of our users.
- Hiding the "pop out / collapse sidebar" links from screen readers makes a lot of sense... I'm a bit worried, however, that that will affect users that are using both a screen reader and a screen. :/ I don't think we have a clear solution to this problem at the moment, and that's probably something the CSSWG needs to address. I'm going to lean on the safe side and leave them alone for now.

The above are all wontfix, as explained. Below are the things I fixed:
- Switched from < nav > to < p >
- Made the Jump to Toc item usable even when the sidebar is popped out. This is currently the first item in the page (thanks to previous a11y feedback ;) and therefore should be easy to get to for keyboard users.
- I wanted to make the collapse/uncollapse link a < button >, but (as noted in the JS source), I don't have a standards-compliant way of addressing the styling correctly. :( This should be fixable once CSSUI4 is completed and implemented, but for now, it's using < a >...
- I've inlined the text and used aria-hidden, as you suggested. As a side note, why is aria-hidden not a boolean attribute? :/

Lastly,
- I have no idea what to replace "Collapse Sidebar" with, so left it intact for now. If you have a better suggestion, let me know asap, and I'll try (though I can't guarantee) to have it fixed for this release.

Thanks!

**Closed as completed by fantasai** 2016-02-20 04:35 UTC

**Comment by thierryk** [comment] 2016-02-20 18:06
What about adding a [`accesskey`](http://webaim.org/techniques/keyboard/accesskey)? I'm not sure what **key** would be best to use but I could ask around if you're willing to add one. 

Regarding "Collapse Sidebar", I'm sorry but I have no idea either.

Thanks!

**Comment by fantasai** [comment] 2016-02-22 04:02
I think the page you link here makes a good case that accesskey isn't necessarily a good idea. :) Probably for gmail or something like that it's worth the learning curve, and therefore worth having; but here I'd rather not interfere with browser chrome. The Jump to ToC link _is_ the very first link in the document, though, so it should be quite easy to get to the ToC even without the access key.

**Comment by thierryk** [comment] 2016-02-22 17:43
A "jump" link is meant to let users skip part of a document while a `accesskey` helps users reach a specific section **regardless of where they are in that document**. 
SR users can navigate via headings, landmarks, etc. but sighted keyboard users do not have a mean to _skip_ tab stops (i.e. links)&mdash;which can be very painful in documents that contain many many links.
I truly believe that such pages are the best example of when a `accesskey` _should_ be implemented. 

> I'd rather not interfere with browser chrome.

This is why I suggested we could ask the #a11y community what `key` we should be using.

Thanks!

**Comment by fantasai** [comment] 2016-02-23 02:45
Ctrl+L then Tab works for me.

**Comment by thierryk** [comment] 2016-02-23 03:10
You mean `Ctrl+L` > `tab` > `enter` in Chrome and `Ctrl+L` > `tab` > `tab` > `tab` > `enter` In Firefox and potentially many more tabs in Safari depending on toolbar customization?
Yeah, I guess that'll work for "power" users (those who know how to focus on the URL).

Thanks!
