### ISSUE TITLE
popping out side bar on mobile 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/tr-design#83] opened 2016-03-16 14:22 UTC
The ability to pop out the side bar on iOS causes some really strange behaviour (it floats over everything, but content is still scrollable). Should that option be available on mobile at all?

**Comment by fantasai** [comment] 2016-03-16 21:27
I don't really see why not. Maybe you want to look at the ToC, but decide to stay where you are?

Not sure what the iOS problem is, since I don't have an iOS device. It seems to work sensibly on Android?

**Comment by marcoscaceres** [comment] 2016-03-17 00:36
Screenshot from iOS. 
![2016-03-17 01 15 33](https://cloud.githubusercontent.com/assets/870154/13832877/65fd1e62-ec34-11e5-9267-86fc4f67cba6.png)

**Comment by marcoscaceres** [comment] 2016-03-17 00:38
Note the bottom area appears and disappears almost at random. That little area is scrollable (which is pretty funny), but the TOC doesn't scroll and just sits there. The whole thing is pretty borked.

**Comment by marcoscaceres** [comment] 2016-03-17 00:39
This was the doc I was looking at: http://usecases.responsiveimages.org/

**Comment by fantasai** [comment] 2016-03-17 21:00
Wow, that page looks super messed up. It's missing the left side margin, for one. And trying to scroll the pop-out toc flickers weirdly on Android. But the ToC otherwise works fine. Can you reproduce the problem on anything other than an iOS device? It's going to be hard to debug if it's only broken on iPhones.

**Comment by fantasai** [comment] 2016-03-17 21:01
Also, can you reproduce the problem on http://fantasai.inkedblade.net/style/design/w3c-restyle/2016/sample ?

**Comment by marcoscaceres** [comment] 2016-03-17 21:52
Confirmed, also happens on the sample in iOS. Will attach screenshot when I get to work. 

Can maybe try to debug it later today.

**Comment by fantasai** [comment] 2016-05-18 00:42
I can't really debug this, it appears to be a browser bug rather than a stylesheet bug, and it doesn't seem to interfere with using the specs, so closing as WONTFIX. Feel free to reopen if you have a fix, though.

**Closed as completed by fantasai** 2016-05-18 00:42 UTC
Labels: wontfix

**Comment by marcoscaceres** [comment] 2016-05-19 03:42
It seems sad that we are not bothering to cater to the second most used mobile browsing platform. I read a lot of specs on my iPhone and I'm sure I'm not alone. Please leave this open and I'll try to find time to attempt a fix.
