### ISSUE TITLE
prevent the page from scrolling horizontally on narrow screens

### ISSUE THREAD

**Issue by jensimmons** [w3c/tr-design#38] opened 2016-01-12 21:29 UTC
Right now, if you go to http://fantasai.inkedblade.net/style/design/w3c-restyle/2016/sample on a small screen (any brand phone with any OS & browser), the page scrolls sideways, horizontally back and forth, while you are trying to read and trying to scrolling vertically. This makes reading the document very hard, especially since these are long documents. 

You can replicate this on a traditional computer by making the browser window very narrow. 

Why are the horizontal scroll bars appearing? Because some of the content is too wide — especially the tables. 

The solution is to make the tables stay inside the available space, and not let them scroll-jack the whole page. 

This code solves most of the problem:

```
table {
  display: block;
  overflow-x: auto;
}
```

Now, we were having a long conversation about this on Twitter, and I saw people complaining that then you have to scroll sideways to see the whole table. Yes, that's true. And likely not ideal, but you'd have to scroll sideways to see the whole table anyway. To me, the addition of this code does not make the experience of seeing the table worse. It does make the experience of seeing everything else much better. In fact, imo, no one will look at the tables without this code, because no one will scroll down far enough to get to the tables. 

If you disagree, please at least first test this on a touch screen smart phone of your choice. http://fantasai.inkedblade.net/style/design/w3c-restyle/2016/sample
In fact, test both — with and without this change — and see what it's like on a touch screen. Trying to guess what the experience is like from imaging it is unlikely to produce good information for making a decision. No less than 9 people complained on Twitter about this experience. It was by far, the number one bug report.

If this simple solution doesn't provide a nice-enough table experience, then a second-level improvement would be to find a better solution for the tables. Fantasai has pointed out that there are many kinds of tables, with many different data structures. Any solution needs to be universal and independent of knowing what the content in the table is. 

A web search for "responsive tables" will provide a plethora of options. Some require a consistent and known data structure, so those are out. Doing quick search this morning I found:
http://exisweb.net/responsive-table-plugins-and-patterns
https://css-tricks.com/responsive-data-tables/
https://github.com/filamentgroup/tablesaw

My recommendation is to add `table { display: block; overflow-x: auto; }` as a first step. Then if time and energy allows, look into a more complex option for making the tables responsive. 

BTW, this solution will have no affect on tables or other content when the screen is wider. It only affects whether the table alone gets a horizontal scroll bar or the whole page gets one.

/cc @fantasai @patrickkettner

**Comment by jensimmons** [comment] 2016-01-12 21:32
Here's a screenshot of the experience without this fix: 

![img_1218](https://cloud.githubusercontent.com/assets/108474/12277581/15479a28-b94a-11e5-9d24-d5bc8a2b83eb.jpg)

**Comment by jensimmons** [comment] 2016-01-12 21:37
The tables are creating the worst of the horizontal scrolling, but there is a second bug also creating sideways movement. 

On a screen narrower than 450px wide, `ul.index` gets wider than the available space. If I toss this code at it `ul.index li { margin-left: -100x }`, then the scrolling goes away. That's how I know the problem is with the Index, perhaps specifically with the list items in the index. But of course, moving all the list items to the left like that is not a fix. I couldn't track down what's wrong exactly, but a bit more looking into it should reveal which item is too wide. Make it narrow enough to fix in the available space, or otherwise control the overflow, and the scrolling will go away.

**Comment by fantasai** [comment] 2016-01-12 23:56
I think I know what's happening with the index. We'll consider that a separate bug. Wrt tables, none of the solutions you link to will work for the kinds of tables we need to handle. They only work for basic data tables with a simple structure. We can do what you're suggesting and make the tables scrollable, but my concern there is that on tables that are longer than the viewport, it becomes difficult to scroll sideways. If people think that's less of a problem than having a horizontal scrollbar, then I can accept your fix. But I'm not sure.

**Comment by fantasai** [comment] 2016-01-13 00:18
Non-table issue should be fixed. Lemme know if it's not.

**Comment by jensimmons** [comment] 2016-01-13 00:50
Sounds like this needs testing. We could create two similar pages, one with each option, and poll people to see which they like better / find more useable.

**Comment by fantasai** [comment] 2016-01-13 07:16
http://fantasai.inkedblade.net/style/design/w3c-restyle/2016/sampleA#property-index
http://fantasai.inkedblade.net/style/design/w3c-restyle/2016/sampleB#property-index

**Comment by tripu** [comment] 2016-01-13 07:38
I personally prefer option B; what is outside wide tables stays fixed, and it prevents the kind of unintended horizontal scrolling that @jensimmons mentioned.

**Comment by justmarkup** [comment] 2016-01-13 07:41
SampleB looks good for me on Android 5.0 with a 360x640 screen.

To prevent horizontal scrolling caused by longs words or URLs you may also consider adding the following CSS:

```
* {
  overflow-wrap: break-word;
  word-wrap: break-word;
  -webkit-hyphens: auto;
  -ms-hyphens: auto;
  -moz-hyphens: auto;
  hyphens: auto;
}
```

**Comment by fantasai** [comment] 2016-01-13 07:42
SampleB looks great of course, but how easy is it to scroll the table to see all of it?

**Comment by yatil** [comment] 2016-01-13 12:37
Strongly supporting B here as well. It also avoids unintentional horizontal scrolling and is easier for users to interact with.

**Comment by fantasai** [comment] 2016-01-13 21:49
Okay, so long as you all think this is worth the price for long tables on desktop (which then become super unweildy as you scroll down to scroll right then scroll back up to see what you scrolled...)

**Comment by yatil** [comment] 2016-01-13 21:50
You can have it non-scrolling on the desktop with a media query, if you think that improves stuff :-)

**Comment by jensimmons** [comment] 2016-01-13 22:36
Oh terrific. Thanks for accepting this suggestion. I really do think it makes for a better experience. 

Test B from above is still a bit wonky. It would be easy to both scroll the page vertically and scroll the tables horizontally if there were no movement at all side-to-side. I think now the extra-long links are what causes the content to make it's container bigger than the viewport. @justmarkup's suggestion from https://github.com/w3c/tr-design/issues/38#issuecomment-171204886 would fix that. 

```
* {
  overflow-wrap: break-word;
  word-wrap: break-word;
  -webkit-hyphens: auto;
  -ms-hyphens: auto;
  -moz-hyphens: auto;
  hyphens: auto;
}
```

**Comment by fantasai** [comment] 2016-01-13 22:44
Okay, well, that broke table styling. It really requires a wrapper element. :/

**Comment by fantasai** [comment] 2016-01-13 22:49
overflow-wrap and hyphens inherit, and should therefore pretty much never be used with the \* selector, btw.

**Comment by yatil** [comment] 2016-01-13 22:49
Well, both overflow/word-wrap and hyphens inherit, so 

``` css
body {
  overflow-wrap: break-word;
  word-wrap: break-word;
  -webkit-hyphens: auto;
  -ms-hyphens: auto;
  -moz-hyphens: auto;
  hyphens: auto;
}
```

is sufficient. And then you could do this for tables:

``` css
table {
  display: block;
  overflow-x: auto;
  overflow-wrap: normal;
  word-wrap: normal;
  -webkit-hyphens: manual;
  -ms-hyphens: manual;
  -moz-hyphens: manual;
}
```

**Comment by fantasai** [comment] 2016-01-13 23:02
Okay. But I can't do display: block on tables, it breaks the table styling. Either the spec generators need to add a wrapper element, or we do that in JS on load.

**Comment by fantasai** [comment] 2016-01-15 01:20
Rejiggered the overflow code, and added JS to automatically wrap tables. Closing, reopen if something's not right.

**Closed as completed by fantasai** 2016-01-15 01:20 UTC

**Comment by sindre** [comment] 2016-01-20 15:20
A almost similiar table implementation on the following site has a small additional UX detail. https://www.wien.gv.at/forschung/laboratorien/umweltmedizin/wasserhygiene/badewasserqualitaet/natur.html
The small shadow on the right, gives the user a indication of more content. Could be a nice little upgrade.

**Comment by fantasai** [comment] 2016-01-20 15:36
They're detecting overflow via JS and adding a wrapper element on the fly; this code just wraps all tables on load, and doesn't know whether they overflow. I think the shadow is nice, but I'm also a little wary of making perf stress tests like the HTML5 spec even worse. ;)

**Comment by justmarkup** [comment] 2016-01-21 12:27
You can also add shadows with CSS only and I think it would be a great enhancement in supported browsers.

Demo and Code: http://jsbin.com/atarOxU/1/edit?html,css,output

**Comment by sindre** [comment] 2016-01-22 14:09
Realy nice Implementation. Like how the shadow changes from right to left when scrolling. In Android Chrome the shadows stays only on the right, still better then without shadow.

**Comment by fantasai** [comment] 2016-01-23 07:27
That's very cool, but it doesn't really work on things that aren't black/gray text on a white background. :/
